name: Build

on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-job:
    runs-on: windows-latest
    outputs:
      buildRunner: ${{runner.name}}
    steps:
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ steps.commonBuildVars.outputs.dotnetVersion }}
    
      - name: Get project
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: list  
        run: dir
        
  post-build-job:
    runs-on: ubuntu-latest
    needs: build-job
    
    steps:
    
    - name: Hellow
      shell: bash
      run: echo "hello"
      
    - name: get Runner
      run: echo "${{ needs.build-job.outputs.buildRunner }}"
   
